import type { ExecutiveQueryId, SupportedExecutiveQuery } from "@/lib/executive-natural-language-queries/types";

export const SUPPORTED_EXECUTIVE_QUERIES: SupportedExecutiveQuery[] = [
  {
    id: "applicants_today",
    category: "applicants",
    question: "How many applicants applied today?",
    examplePhrases: ["applicants today", "applied today", "new applicants today"],
    previewOnly: true,
  },
  {
    id: "applicants_week",
    category: "applicants",
    question: "How many applicants applied this week?",
    examplePhrases: ["applicants this week", "applied this week", "weekly applicants"],
    previewOnly: true,
  },
  {
    id: "applicants_month",
    category: "applicants",
    question: "How many applicants applied this month?",
    examplePhrases: ["applicants this month", "applied this month", "mtd applicants"],
    previewOnly: true,
  },
  {
    id: "paperwork_sent_today",
    category: "paperwork",
    question: "How many paperwork packets were sent today?",
    examplePhrases: ["paperwork sent today", "packets sent today", "sent paperwork today"],
    previewOnly: true,
  },
  {
    id: "paperwork_sent_week",
    category: "paperwork",
    question: "How many paperwork packets were sent this week?",
    examplePhrases: ["paperwork sent this week", "packets sent this week"],
    previewOnly: true,
  },
  {
    id: "paperwork_signed_today",
    category: "paperwork",
    question: "How many candidates signed paperwork today?",
    examplePhrases: ["signed paperwork today", "paperwork signed today", "signatures today"],
    previewOnly: true,
  },
  {
    id: "paperwork_auto_sent_today",
    category: "paperwork",
    question: "How many paperwork packets were automatically sent today?",
    examplePhrases: ["automatically sent today", "auto sent paperwork", "auto paperwork today"],
    previewOnly: true,
  },
  {
    id: "paperwork_manual_sent_today",
    category: "paperwork",
    question: "How many paperwork packets were manually sent today?",
    examplePhrases: ["manually sent today", "manual paperwork sends"],
    previewOnly: true,
  },
  {
    id: "paperwork_failed_count",
    category: "paperwork",
    question: "Which paperwork packets failed?",
    examplePhrases: ["paperwork failed", "failed packets", "failed paperwork"],
    previewOnly: true,
  },
  {
    id: "paperwork_waiting_longest",
    category: "paperwork",
    question: "Who has been waiting the longest to sign?",
    examplePhrases: ["waiting longest", "longest to sign", "stalled signatures"],
    previewOnly: true,
  },
  {
    id: "paperwork_top_recruiter_today",
    category: "paperwork",
    question: "Which recruiter sent the most paperwork today?",
    examplePhrases: ["recruiter sent most paperwork", "top recruiter paperwork"],
    previewOnly: true,
  },
  {
    id: "paperwork_ready_for_auto",
    category: "paperwork",
    question: "How many candidates are ready for automatic paperwork?",
    examplePhrases: ["ready for automatic paperwork", "ready for auto send", "auto paperwork eligible"],
    previewOnly: true,
  },
  {
    id: "paperwork_waiting_signature",
    category: "paperwork",
    question: "How many candidates are waiting for signatures?",
    examplePhrases: ["waiting for signatures", "awaiting signature", "pending signatures"],
    previewOnly: true,
  },
  {
    id: "paperwork_blocked_auto",
    category: "paperwork",
    question: "Which candidates are blocked from automatic paperwork?",
    examplePhrases: ["blocked from automatic", "blocked paperwork", "cannot auto send"],
    previewOnly: true,
  },
  {
    id: "paperwork_oldest_pending",
    category: "paperwork",
    question: "What is the oldest pending paperwork packet?",
    examplePhrases: ["oldest pending paperwork", "oldest packet", "longest pending packet"],
    previewOnly: true,
  },
  {
    id: "paperwork_failed_today",
    category: "paperwork",
    question: "What paperwork failed today?",
    examplePhrases: ["failed today", "paperwork failed today", "what failed today"],
    previewOnly: true,
  },
  {
    id: "brief_how_are_we_doing",
    category: "brief",
    question: "How are we doing today?",
    examplePhrases: ["how are we doing", "how are we doing today", "status today"],
    previewOnly: true,
  },
  {
    id: "brief_recruiting_summary",
    category: "brief",
    question: "Give me today's recruiting summary.",
    examplePhrases: ["today's recruiting summary", "recruiting summary today", "daily recruiting summary"],
    previewOnly: true,
  },
  {
    id: "brief_what_changed",
    category: "brief",
    question: "What changed today?",
    examplePhrases: ["what changed today", "what's different today", "changes today"],
    previewOnly: true,
  },
  {
    id: "brief_needs_attention",
    category: "brief",
    question: "What needs attention today?",
    examplePhrases: ["what needs attention", "needs attention today", "what should I focus on"],
    previewOnly: true,
  },
  {
    id: "communication_sent_today",
    category: "communication",
    question: "How many communications were sent today?",
    examplePhrases: ["communications sent today", "how many communications today", "messages sent today"],
    previewOnly: true,
  },
  {
    id: "communication_needs_reminders",
    category: "communication",
    question: "Who still needs reminders?",
    examplePhrases: ["who still needs reminders", "needs reminders", "pending reminders"],
    previewOnly: true,
  },
  {
    id: "communication_no_response",
    category: "communication",
    question: "Which candidates have not responded?",
    examplePhrases: ["not responded", "no response", "candidates have not responded"],
    previewOnly: true,
  },
  {
    id: "communication_failures",
    category: "communication",
    question: "Show communication failures.",
    examplePhrases: ["communication failures", "failed communications", "show communication failures"],
    previewOnly: true,
  },
  {
    id: "communication_welcome_today",
    category: "communication",
    question: "Who received welcome emails today?",
    examplePhrases: ["welcome emails today", "who received welcome", "welcome email today"],
    previewOnly: true,
  },
  {
    id: "communication_waiting_approval",
    category: "communication",
    question: "What communications are waiting approval?",
    examplePhrases: ["waiting approval", "communications waiting approval", "pending approval communications"],
    previewOnly: true,
  },
  {
    id: "orchestrator_system_status",
    category: "orchestrator",
    question: "What is the system doing right now?",
    examplePhrases: ["what is the system doing", "system status", "what is happening now"],
    previewOnly: true,
  },
  {
    id: "orchestrator_automation_blocked",
    category: "orchestrator",
    question: "Where is automation blocked?",
    examplePhrases: ["where is automation blocked", "automation blocked", "blocked automation"],
    previewOnly: true,
  },
  {
    id: "orchestrator_engine_waiting",
    category: "orchestrator",
    question: "Which engine is waiting?",
    examplePhrases: ["which engine is waiting", "engine waiting", "waiting engine"],
    previewOnly: true,
  },
  {
    id: "orchestrator_candidates_stuck",
    category: "orchestrator",
    question: "Which candidates are stuck?",
    examplePhrases: ["candidates are stuck", "stuck candidates", "which candidates stuck"],
    previewOnly: true,
  },
  {
    id: "orchestrator_today_workflow",
    category: "orchestrator",
    question: "Show today's workflow.",
    examplePhrases: ["today's workflow", "show today workflow", "workflow today"],
    previewOnly: true,
  },
  {
    id: "orchestrator_hiring_blockers",
    category: "orchestrator",
    question: "What is preventing hiring?",
    examplePhrases: ["preventing hiring", "hiring blockers", "what is blocking hiring"],
    previewOnly: true,
  },
  {
    id: "orchestrator_next_actions",
    category: "orchestrator",
    question: "What will happen next?",
    examplePhrases: ["what will happen next", "next actions", "what happens next"],
    previewOnly: true,
  },
  {
    id: "orchestrator_recruiter_automated",
    category: "orchestrator",
    question: "How much recruiter work has been automated?",
    examplePhrases: ["recruiter work automated", "how much automated", "recruiter automation"],
    previewOnly: true,
  },
  {
    id: "orchestrator_workflow_attention",
    category: "orchestrator",
    question: "Which workflow needs attention?",
    examplePhrases: ["workflow needs attention", "which workflow attention", "needs attention workflow"],
    previewOnly: true,
  },
  {
    id: "operations_anything_broken",
    category: "operations",
    question: "Is anything broken?",
    examplePhrases: ["is anything broken", "anything broken", "is something broken"],
    previewOnly: true,
  },
  {
    id: "operations_critical_issues",
    category: "operations",
    question: "Show critical issues.",
    examplePhrases: ["critical issues", "show critical issues", "critical problems"],
    previewOnly: true,
  },
  {
    id: "operations_needs_attention",
    category: "operations",
    question: "What needs attention now?",
    examplePhrases: ["what needs attention now", "needs attention now", "attention now"],
    previewOnly: true,
  },
  {
    id: "operations_unhealthy_workflows",
    category: "operations",
    question: "Which workflows are unhealthy?",
    examplePhrases: ["unhealthy workflows", "which workflows unhealthy", "workflows unhealthy"],
    previewOnly: true,
  },
  {
    id: "operations_recruiting_slowdown",
    category: "operations",
    question: "Why is recruiting slowing down?",
    examplePhrases: ["recruiting slowing down", "why recruiting slow", "slowdown recruiting"],
    previewOnly: true,
  },
  {
    id: "operations_leadership_fix_today",
    category: "operations",
    question: "What should leadership fix today?",
    examplePhrases: ["leadership fix today", "what should leadership fix", "fix today"],
    previewOnly: true,
  },
  {
    id: "operations_biggest_risk",
    category: "operations",
    question: "What is the biggest operational risk?",
    examplePhrases: ["biggest operational risk", "biggest risk", "operational risk"],
    previewOnly: true,
  },
  {
    id: "operations_problem_tomorrow",
    category: "operations",
    question: "What will become a problem tomorrow?",
    examplePhrases: ["problem tomorrow", "become a problem tomorrow", "tomorrow risk"],
    previewOnly: true,
  },
  {
    id: "decisions_what_next",
    category: "decisions",
    question: "What should the system do next?",
    examplePhrases: ["what should the system do next", "what should happen next", "system do next"],
    previewOnly: true,
  },
  {
    id: "decisions_best",
    category: "decisions",
    question: "What is the best decision?",
    examplePhrases: ["best decision", "what is the best decision", "top decision"],
    previewOnly: true,
  },
  {
    id: "decisions_why_recommended",
    category: "decisions",
    question: "Why did the AI recommend this?",
    examplePhrases: ["why did the ai recommend", "why recommend this", "why this recommendation"],
    previewOnly: true,
  },
  {
    id: "decisions_need_approval",
    category: "decisions",
    question: "Which decisions need approval?",
    examplePhrases: ["decisions need approval", "which decisions need approval", "need human approval"],
    previewOnly: true,
  },
  {
    id: "decisions_high_confidence",
    category: "decisions",
    question: "What high-confidence actions exist?",
    examplePhrases: ["high confidence actions", "high-confidence actions", "confident recommendations"],
    previewOnly: true,
  },
  {
    id: "decisions_low_confidence",
    category: "decisions",
    question: "Show low-confidence recommendations.",
    examplePhrases: ["low confidence recommendations", "low-confidence recommendations", "uncertain recommendations"],
    previewOnly: true,
  },
  {
    id: "decisions_safest_action",
    category: "decisions",
    question: "What is the safest action?",
    examplePhrases: ["safest action", "what is the safest action", "lowest risk action"],
    previewOnly: true,
  },
  {
    id: "decisions_highest_value",
    category: "decisions",
    question: "What decision creates the most value?",
    examplePhrases: ["most value decision", "highest value recommendation", "biggest opportunity"],
    previewOnly: true,
  },
  {
    id: "governance_auto_allowed",
    category: "governance",
    question: "What can the system do automatically?",
    examplePhrases: ["what can the system do automatically", "auto approved decisions", "automatic actions allowed"],
    previewOnly: true,
  },
  {
    id: "governance_requires_approval",
    category: "governance",
    question: "What requires approval?",
    examplePhrases: ["what requires approval", "decisions need approval", "approval required"],
    previewOnly: true,
  },
  {
    id: "governance_blocked",
    category: "governance",
    question: "What is blocked by policy?",
    examplePhrases: ["blocked by policy", "what is blocked", "policy blocks"],
    previewOnly: true,
  },
  {
    id: "governance_why_not_automated",
    category: "governance",
    question: "Why can't this be automated?",
    examplePhrases: ["why can't this be automated", "why not automated", "automation blocked why"],
    previewOnly: true,
  },
  {
    id: "governance_pilot_eligible",
    category: "governance",
    question: "Which decisions are pilot eligible?",
    examplePhrases: ["pilot eligible", "which decisions pilot", "pilot market decisions"],
    previewOnly: true,
  },
  {
    id: "governance_safe_to_approve",
    category: "governance",
    question: "What is safe to approve?",
    examplePhrases: ["safe to approve", "what is safe to approve", "low risk approve"],
    previewOnly: true,
  },
  {
    id: "governance_executive_approval",
    category: "governance",
    question: "What needs executive approval?",
    examplePhrases: ["executive approval", "needs executive approval", "leadership approval required"],
    previewOnly: true,
  },
  {
    id: "governance_blocking_rules",
    category: "governance",
    question: "What rules are stopping automation?",
    examplePhrases: ["rules stopping automation", "blocking rules", "what rules block automation"],
    previewOnly: true,
  },
];

/** Reserved for future queries — register definitions only, wire handlers separately. */
export const FUTURE_EXECUTIVE_QUERY_STUBS = [
  "ready_for_work_today",
  "candidates_in_onboarding",
  "human_review_queue",
  "workforce_recommendations",
  "markets_needing_coverage",
  "recruiter_leaderboard",
  "dm_performance",
  "open_stores",
  "capacity_planning",
  "candidate_grades",
] as const;

export function getSupportedExecutiveQuery(id: ExecutiveQueryId): SupportedExecutiveQuery | null {
  return SUPPORTED_EXECUTIVE_QUERIES.find((row) => row.id === id) ?? null;
}

export function listSupportedExecutiveQueries(): SupportedExecutiveQuery[] {
  return [...SUPPORTED_EXECUTIVE_QUERIES];
}
