import type {
  P1864SchedulerRecord,
  P1864WriterRecord,
} from "@/lib/p186-4-lifecycle-reconciler/types";

/**
 * Central shadow-only writer registry.
 * Does NOT enable/disable production writers.
 */
export const P1864_WRITER_REGISTRY: readonly P1864WriterRecord[] = [
  {
    writerId: "candidate-workflow-store-core",
    module: "candidate-workflow-store",
    filePaths: ["src/lib/candidate-workflow-store.ts"],
    statesWritable: ["any CandidateWorkflowStatus", "any PaperworkStatus"],
    ownedTransitions: ["*→production_workflow"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "library",
    entryPoint: "upsertCandidateWorkflow",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: null,
    priority: 100,
    deprecationStatus: "active",
    productionUsage: "canonical production mutator",
    overlapNotes: "All production writers funnel here",
    retirementRecommendation: "keep",
  },
  {
    writerId: "api-candidates-workflows",
    module: "candidates workflows API",
    filePaths: ["src/app/api/candidates/workflows/route.ts"],
    statesWritable: ["operator-supplied workflowStatus"],
    ownedTransitions: ["manual_operator_update"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/candidates/workflows",
    idempotency: "no",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "approval_to_paperwork_needed",
    priority: 80,
    deprecationStatus: "active",
    productionUsage: "UI/manual operator writes",
    overlapNotes: "Overlaps P97 and P186.3 approvals",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p83-candidate-advancement",
    module: "candidate-advancement-engine",
    filePaths: [
      "src/lib/candidate-advancement-engine/apply-candidate-advancements.ts",
      "src/lib/p62-p83-approval-preview/build-p62-p83-approval-preview.ts",
    ],
    statesWritable: ["Paperwork Needed", "recommendedStage"],
    ownedTransitions: ["Qualified→Paperwork Needed"],
    allowedSourceStates: ["Qualified", "Needs Review"],
    allowedDestinationStates: ["Paperwork Needed"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/orchestrator",
    entryPoint: "applyCandidateAdvancements via P151",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P151_AUTONOMOUS_ADVANCEMENT_ENABLED",
    conflictGroup: "approval_to_paperwork_needed",
    priority: 40,
    deprecationStatus: "legacy_active",
    productionUsage: "advancement via P151",
    overlapNotes: "Overlaps P97, P158, P186.3",
    retirementRecommendation: "freeze_later",
  },
  {
    writerId: "p97-approval-mode-persist",
    module: "approval-mode-production",
    filePaths: [
      "src/lib/approval-mode-production/persist-approved-candidate.ts",
      "src/app/api/approval-mode-production/route.ts",
    ],
    statesWritable: ["Paperwork Needed"],
    ownedTransitions: ["Qualified→Paperwork Needed"],
    allowedSourceStates: ["Qualified", "Needs Review", "Applied"],
    allowedDestinationStates: ["Paperwork Needed"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/approval-mode-production",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "approval_to_paperwork_needed",
    priority: 55,
    deprecationStatus: "legacy_active",
    productionUsage: "executive approval persist",
    overlapNotes: "Overlaps P186.3 approve_hiring_recommendation",
    retirementRecommendation: "observe",
  },
  {
    writerId: "p106-autonomous-paperwork-engine",
    module: "p106-autonomous-paperwork-engine",
    filePaths: [
      "src/lib/p106-autonomous-paperwork-engine/run-autonomous-paperwork-engine.ts",
      "src/app/api/autonomous-paperwork-engine/run/route.ts",
    ],
    statesWritable: ["Paperwork Sent", "failed"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/script",
    entryPoint: "/api/autonomous-paperwork-engine/run",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P84_LIVE_SEND",
    conflictGroup: "paperwork_send",
    priority: 20,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "legacy send path",
    overlapNotes: "Superseded by P184/P185",
    retirementRecommendation: "retire_later",
  },
  {
    writerId: "p1061-autonomous-paperwork-runner",
    module: "autonomous-paperwork-runner",
    filePaths: [
      "src/lib/autonomous-paperwork-runner/run-autonomous-paperwork-runner.ts",
      "src/app/api/autonomous-paperwork-runner/start/route.ts",
    ],
    statesWritable: ["Paperwork Sent via P106"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "interval",
    entryPoint: "/api/autonomous-paperwork-runner/start",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "AUTONOMOUS_PAPERWORK_RUNNER_SCHEDULE_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 15,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "scheduled P106 wrapper",
    overlapNotes: "Overlaps P125/P136/P185",
    retirementRecommendation: "retire_later",
  },
  {
    writerId: "p107-paperwork-monitor",
    module: "paperwork-monitor",
    filePaths: [
      "src/lib/paperwork-monitor/reconcile-paperwork-candidate.ts",
      "src/app/api/paperwork-monitor/run/route.ts",
    ],
    statesWritable: ["viewed", "Signed", "Ready for MEL"],
    ownedTransitions: ["Paperwork Sent→Signed", "Signed→Ready for MEL"],
    allowedSourceStates: ["Paperwork Sent", "Signed"],
    allowedDestinationStates: ["Signed", "Ready for MEL"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/interval",
    entryPoint: "/api/paperwork-monitor/run",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "signature_to_mel",
    priority: 70,
    deprecationStatus: "active",
    productionUsage: "poll Dropbox + promote MEL",
    overlapNotes: "Overlaps Dropbox webhook and P84 monitor",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p122-controlled-live-pilot",
    module: "p122-controlled-live-paperwork-pilot",
    filePaths: [
      "src/lib/p122-controlled-live-paperwork-pilot/run-controlled-live-pilot.ts",
      "src/lib/controlled-live-send/execute-controlled-live-send.ts",
    ],
    statesWritable: ["Paperwork Sent"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "orchestrator",
    entryPoint: "runControlledLivePaperworkPilot",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "AUTONOMOUS_PAPERWORK_LIVE_PILOT_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 25,
    deprecationStatus: "legacy_active",
    productionUsage: "controlled live pilot send",
    overlapNotes: "Used by P123/P125; superseded by P184",
    retirementRecommendation: "freeze_later",
  },
  {
    writerId: "p123-paperwork-cycle-orchestrator",
    module: "autonomous-paperwork-orchestrator",
    filePaths: [
      "src/lib/autonomous-paperwork-orchestrator/execute-paperwork-cycle.ts",
      "src/app/api/paperwork-cycle/route.ts",
    ],
    statesWritable: ["Paperwork Sent via P122"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/paperwork-cycle",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "paperwork_send",
    priority: 22,
    deprecationStatus: "legacy_active",
    productionUsage: "executeOne cycle",
    overlapNotes: "Used by P125/P136",
    retirementRecommendation: "freeze_later",
  },
  {
    writerId: "p125-production-runner",
    module: "p125-autonomous-paperwork-production-runner",
    filePaths: [
      "src/lib/p125-autonomous-paperwork-production-runner/run-production-runner.ts",
      "scripts/p125-autonomous-paperwork-production-runner.ts",
    ],
    statesWritable: ["Paperwork Sent via cycle"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "interval",
    entryPoint: "startProductionRunner",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P125_RUNNER_CONTINUOUS_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 18,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "5m continuous runner",
    overlapNotes: "Overlaps P136 and P185",
    retirementRecommendation: "retire_later",
  },
  {
    writerId: "p136-paperwork-scheduler",
    module: "p136-autonomous-paperwork-scheduler",
    filePaths: [
      "src/lib/p136-autonomous-paperwork-scheduler/run-scheduler-cycle.ts",
      "src/app/api/autonomous-paperwork-scheduler/start/route.ts",
    ],
    statesWritable: ["Paperwork Sent via cycle"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "interval",
    entryPoint: "/api/autonomous-paperwork-scheduler/start",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "paperwork_send",
    priority: 17,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "in-process 5m scheduler",
    overlapNotes: "Overlaps P125/P185",
    retirementRecommendation: "retire_later",
  },
  {
    writerId: "p148-autonomous-recruiting-orchestrator",
    module: "p148-autonomous-recruiting-orchestrator",
    filePaths: [
      "src/lib/p148-autonomous-recruiting-orchestrator/orchestrator-store.ts",
      "scripts/p148-autonomous-recruiting-orchestrator.ts",
    ],
    statesWritable: ["delegates to downstream"],
    ownedTransitions: ["orchestration"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: false,
    shadowOnly: false,
    trigger: "interval",
    entryPoint: "scripts/p148-autonomous-recruiting-orchestrator.ts",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "AUTONOMOUS_RECRUITING_ENABLED",
    conflictGroup: "continuous_orchestration",
    priority: 12,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "predecessor continuous orchestrator",
    overlapNotes: "Superseded by P154.7/P169",
    retirementRecommendation: "retire_later",
  },
  {
    writerId: "p151-pipeline-advancement",
    module: "p151-autonomous-candidate-advancement",
    filePaths: [
      "src/lib/p151-autonomous-candidate-advancement/advance-candidate-pipeline.ts",
      "src/app/api/recruiting/candidate-pipeline-advancement/route.ts",
    ],
    statesWritable: ["Paperwork Needed", "assignments"],
    ownedTransitions: ["Applied→Needs Review", "Qualified→Paperwork Needed"],
    allowedSourceStates: ["Applied", "Needs Review", "Qualified"],
    allowedDestinationStates: ["Needs Review", "Paperwork Needed"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/script/autopilot",
    entryPoint: "/api/recruiting/candidate-pipeline-advancement",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P151_AUTONOMOUS_ADVANCEMENT_ENABLED",
    conflictGroup: "approval_to_paperwork_needed",
    priority: 75,
    deprecationStatus: "active",
    productionUsage: "pipeline advancement",
    overlapNotes: "Composes P83 + assignment engines",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p152-immediate-paperwork",
    module: "p152-immediate-paperwork-policy",
    filePaths: [
      "src/lib/p152-immediate-paperwork-policy/execute-immediate-paperwork-policy.ts",
    ],
    statesWritable: ["Paperwork Sent"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "orchestrator",
    entryPoint: "executeImmediatePaperworkPolicy",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P152_IMMEDIATE_PAPERWORK_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 65,
    deprecationStatus: "active",
    productionUsage: "live send via P154/P159",
    overlapNotes: "Overlaps P184 production send",
    retirementRecommendation: "observe",
  },
  {
    writerId: "p154-controlled-autopilot",
    module: "p154-controlled-production-autopilot-activation",
    filePaths: [
      "src/lib/p154-controlled-production-autopilot-activation/execute-controlled-production-autopilot.ts",
    ],
    statesWritable: ["assignment + Paperwork Needed + Paperwork Sent"],
    ownedTransitions: ["autopilot_cycle"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["Paperwork Needed", "Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "script/API",
    entryPoint: "executeControlledProductionAutopilot",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P154_CONTROLLED_PRODUCTION_AUTOPILOT_ENABLED",
    conflictGroup: "continuous_orchestration",
    priority: 72,
    deprecationStatus: "active",
    productionUsage: "orchestrates P151+P152",
    overlapNotes: "Called by P154.7",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p1547-continuous-recruiting-runner",
    module: "p154-continuous-autonomous-recruiting-runner",
    filePaths: [
      "src/lib/p154-continuous-autonomous-recruiting-runner/run-autonomous-recruiting-cycle.ts",
      "src/app/api/recruiting/autonomous/run/route.ts",
      "scripts/p154.7-continuous-runner.ts",
    ],
    statesWritable: ["via P154 autopilot + monitor"],
    ownedTransitions: ["continuous_cycle"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "daemon/interval",
    entryPoint: "/api/recruiting/autonomous/run",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P154_CONTINUOUS_ENABLED",
    conflictGroup: "continuous_orchestration",
    priority: 78,
    deprecationStatus: "active",
    productionUsage: "central continuous loop ~10m",
    overlapNotes: "Invoked by P159/P169/P171",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p158-post-assignment-transition",
    module: "p158-post-assignment-workflow-transition",
    filePaths: [
      "src/lib/p158-post-assignment-workflow-transition/transition-engine.ts",
    ],
    statesWritable: ["Paperwork Needed"],
    ownedTransitions: ["assigned→Paperwork Needed"],
    allowedSourceStates: ["Applied", "Needs Review", "Qualified"],
    allowedDestinationStates: ["Paperwork Needed"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/orchestrator",
    entryPoint: "transition-engine",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "approval_to_paperwork_needed",
    priority: 68,
    deprecationStatus: "active",
    productionUsage: "post-assignment transition",
    overlapNotes: "Overlaps P83/P97/P151",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p159-operations-control-center",
    module: "p159-operations-control-center",
    filePaths: [
      "src/lib/p159-operations-control-center/execute-control-action.ts",
      "src/app/api/recruiting/operations-control-center/control/route.ts",
    ],
    statesWritable: ["via P154.7 when live"],
    ownedTransitions: ["control_plane"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/recruiting/operations-control-center/control",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: "P154_CONTINUOUS_ENABLED",
    conflictGroup: "continuous_orchestration",
    priority: 76,
    deprecationStatus: "active",
    productionUsage: "operator control plane",
    overlapNotes: "Control for P154/P169/P171",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p169-recruiting-orchestrator",
    module: "p169-autonomous-recruiting-orchestrator",
    filePaths: [
      "src/lib/p169-autonomous-recruiting-orchestrator/run-orchestrator-cycle.ts",
      "src/app/api/recruiting/autonomous-orchestrator/control/route.ts",
      "scripts/p169-orchestrator-host.ts",
    ],
    statesWritable: ["via P159→P154.7"],
    ownedTransitions: ["orchestrator_cycle"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "host-interval",
    entryPoint: "runP169OrchestratorCycle",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P169_ORCHESTRATOR_ENABLED",
    conflictGroup: "continuous_orchestration",
    priority: 74,
    deprecationStatus: "active",
    productionUsage: "7m decision orchestrator",
    overlapNotes: "Overlaps P154.7 and P171 intervals",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p171-lifecycle-manager",
    module: "p171-autonomous-candidate-lifecycle-manager",
    filePaths: [
      "src/lib/p171-autonomous-candidate-lifecycle-manager/run-lifecycle-cycle.ts",
      "src/lib/p171-autonomous-candidate-lifecycle-manager/lifecycle-store.ts",
      "src/app/api/recruiting/lifecycle-manager/control/route.ts",
    ],
    statesWritable: ["P171 parallel lifecycle states + may trigger P159/P107"],
    ownedTransitions: ["p171_parallel_lifecycle"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["NEW", "DISCOVERED", "APPROVED", "PAPERWORK_SENT", "READY_FOR_MEL", "COMPLETED"],
    sourceOfAuthority: "shadow",
    productionAuthoritative: false,
    shadowOnly: false,
    trigger: "interval",
    entryPoint: "/api/recruiting/lifecycle-manager/control",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P171_LIFECYCLE_ENABLED",
    conflictGroup: "parallel_lifecycle_store",
    priority: 50,
    deprecationStatus: "active",
    productionUsage: "parallel lifecycle store 15m",
    overlapNotes: "Overlaps P186.1 shadow SM; may call production",
    retirementRecommendation: "observe",
  },
  {
    writerId: "p175-breezy-export-import",
    module: "p175-breezy-export-import",
    filePaths: ["src/lib/p175-breezy-export-import/execute-export-import.ts"],
    statesWritable: ["ingestion + workflow backfill"],
    ownedTransitions: ["Breezy→workflow_seed"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["Applied", "Needs Review", "Qualified"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "script",
    entryPoint: "runBreezyExportImport",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "breezy_ingestion",
    priority: 60,
    deprecationStatus: "active",
    productionUsage: "Breezy import path",
    overlapNotes: "Overlaps P154 CSV import / backfill",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p184-autonomous-paperwork-send-engine",
    module: "p184-autonomous-paperwork-send-engine",
    filePaths: [
      "src/lib/p184-autonomous-paperwork-send-engine/engine.ts",
      "src/lib/p184-autonomous-paperwork-send-engine/sender.ts",
      "src/app/api/p184-autonomous-paperwork-send/route.ts",
    ],
    statesWritable: ["Paperwork Sent/failed"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/script/cron",
    entryPoint: "/api/p184-autonomous-paperwork-send",
    idempotency: "yes",
    auditSupport: "yes",
    featureFlag: "P185_PRODUCTION_AUTOMATION_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 90,
    deprecationStatus: "active",
    productionUsage: "current autonomous send engine",
    overlapNotes: "Preferred send path; overlaps legacy P106/P152",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p185-production-paperwork-runner",
    module: "p185-production-paperwork-automation-runner",
    filePaths: [
      "src/lib/p185-production-paperwork-automation-runner/runner.ts",
      "src/app/api/cron/p185-paperwork-automation/route.ts",
    ],
    statesWritable: ["via P184 send + envelope lifecycle"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent", "envelope_lifecycle"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent", "viewed", "signed"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "cron",
    entryPoint: "/api/cron/p185-paperwork-automation",
    idempotency: "yes",
    auditSupport: "yes",
    featureFlag: "P185_PRODUCTION_AUTOMATION_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 95,
    deprecationStatus: "active",
    productionUsage: "intended production scheduled send */10",
    overlapNotes: "Supersedes P125/P136 continuous",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p186-1-lifecycle-state-machine",
    module: "p186-1-lifecycle-state-machine",
    filePaths: [
      "src/lib/p186-1-lifecycle-state-machine/lifecycleStateMachine.ts",
    ],
    statesWritable: [
      "APPLIED",
      "RECRUITER_REVIEW",
      "HIRING_RECOMMENDATION",
      "OPERATOR_APPROVED",
      "PAPERWORK_NEEDED",
      "PAPERWORK_SENT",
      "VIEWED",
      "SIGNED",
      "ONBOARDING_COMPLETE",
      "READY_FOR_MEL",
      "EXPORTED",
      "BLOCKED",
    ],
    ownedTransitions: ["shadow_lifecycle_*"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["*"],
    sourceOfAuthority: "shadow",
    productionAuthoritative: false,
    shadowOnly: true,
    trigger: "library",
    entryPoint: "LifecycleStateMachine.apply",
    idempotency: "yes",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "parallel_lifecycle_store",
    priority: 45,
    deprecationStatus: "shadow_only",
    productionUsage: "shadow only — never production SoR",
    overlapNotes: "Overlaps P171 parallel store conceptually",
    retirementRecommendation: "shadow_only",
  },
  {
    writerId: "p186-2-event-adapters",
    module: "p186-2-event-adapters",
    filePaths: [
      "src/lib/p186-2-event-adapters/observe.ts",
      "src/lib/p186-2-event-adapters/ingest.ts",
    ],
    statesWritable: ["shadow via P186.1"],
    ownedTransitions: ["observe→shadow"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["shadow states"],
    sourceOfAuthority: "observe",
    productionAuthoritative: false,
    shadowOnly: true,
    trigger: "hooks",
    entryPoint: "observeWorkflowUpsertSafe / observeDropboxSignWebhookSafe",
    idempotency: "yes",
    auditSupport: "yes",
    featureFlag: "P186_SHADOW_INGESTION",
    conflictGroup: "parallel_lifecycle_store",
    priority: 44,
    deprecationStatus: "shadow_only",
    productionUsage: "observe dual-write",
    overlapNotes: "Never mutates production",
    retirementRecommendation: "shadow_only",
  },
  {
    writerId: "p186-3-operator-approval-actions",
    module: "p186-3-operator-lifecycle-queues",
    filePaths: [
      "src/lib/p186-3-operator-lifecycle-queues/approvalActions.ts",
      "src/app/api/recruiting/p186-operator-queues/actions/route.ts",
    ],
    statesWritable: ["Paperwork Needed", "Not Qualified", "Needs Review", "Ready for MEL"],
    ownedTransitions: ["operator_approval→production"],
    allowedSourceStates: ["Qualified", "Needs Review", "Applied"],
    allowedDestinationStates: ["Paperwork Needed", "Not Qualified", "Needs Review", "Ready for MEL"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/recruiting/p186-operator-queues/actions",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P186_APPROVAL_ACTIONS",
    conflictGroup: "approval_to_paperwork_needed",
    priority: 70,
    deprecationStatus: "active",
    productionUsage: "flagged operator approvals via workflow store",
    overlapNotes: "Overlaps P97/workflows API",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p186-4-lifecycle-reconciler",
    module: "p186-4-lifecycle-reconciler",
    filePaths: ["src/lib/p186-4-lifecycle-reconciler/reconciler.ts"],
    statesWritable: ["none — read-only findings"],
    ownedTransitions: [],
    allowedSourceStates: [],
    allowedDestinationStates: [],
    sourceOfAuthority: "observe",
    productionAuthoritative: false,
    shadowOnly: true,
    trigger: "library/API",
    entryPoint: "runShadowLifecycleReconciler",
    idempotency: "yes",
    auditSupport: "yes",
    featureFlag: "P186_RECONCILER_EXECUTION",
    conflictGroup: null,
    priority: 5,
    deprecationStatus: "observe_only",
    productionUsage: "read-only reconciler — never mutates",
    overlapNotes: "Observes all sources; never writes",
    retirementRecommendation: "shadow_only",
  },
  {
    writerId: "dropbox-sign-webhook",
    module: "dropbox-sign-webhook-handler",
    filePaths: [
      "src/lib/dropbox-sign-webhook-handler.ts",
      "src/app/api/dropbox-sign/webhook/route.ts",
    ],
    statesWritable: ["viewed", "Signed"],
    ownedTransitions: ["Paperwork Sent→viewed", "viewed→Signed"],
    allowedSourceStates: ["Paperwork Sent", "viewed"],
    allowedDestinationStates: ["viewed", "Signed"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "webhook",
    entryPoint: "/api/dropbox-sign/webhook",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: null,
    conflictGroup: "signature_to_mel",
    priority: 85,
    deprecationStatus: "active",
    productionUsage: "primary signature authority",
    overlapNotes: "Overlaps P107 polling",
    retirementRecommendation: "keep",
  },
  {
    writerId: "onboarding-send-execute",
    module: "candidate-onboarding-send-queue",
    filePaths: [
      "src/lib/candidate-onboarding-send-queue/execute-onboarding-send.ts",
      "src/app/api/onboarding/send-packet/route.ts",
    ],
    statesWritable: ["Paperwork Sent", "failed"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API/engines",
    entryPoint: "/api/onboarding/send-packet",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "paperwork_send",
    priority: 88,
    deprecationStatus: "active",
    productionUsage: "canonical Dropbox send",
    overlapNotes: "Used by P184 and legacy engines",
    retirementRecommendation: "keep",
  },
  {
    writerId: "onboarding-send-queue-worker",
    module: "candidate-onboarding-send-queue worker",
    filePaths: [
      "src/lib/candidate-onboarding-send-queue/send-queue-worker.ts",
    ],
    statesWritable: ["Paperwork Sent/failed"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "interval",
    entryPoint: "send-queue-worker",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: null,
    conflictGroup: "paperwork_send",
    priority: 30,
    deprecationStatus: "legacy_active",
    productionUsage: "legacy queue worker",
    overlapNotes: "Overlaps P184",
    retirementRecommendation: "freeze_later",
  },
  {
    writerId: "p84-autonomous-paperwork-send",
    module: "autonomous-paperwork-send-engine",
    filePaths: [
      "src/lib/autonomous-paperwork-send-engine/run-autonomous-paperwork-send.ts",
      "src/lib/autonomous-paperwork-send-engine/run-signature-monitoring.ts",
    ],
    statesWritable: ["Paperwork Sent", "Ready for MEL"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent", "Signed→Ready for MEL"],
    allowedSourceStates: ["Paperwork Needed", "Signed"],
    allowedDestinationStates: ["Paperwork Sent", "Ready for MEL"],
    sourceOfAuthority: "legacy",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "orchestrator",
    entryPoint: "runAutonomousPaperworkSend",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: "P84_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 28,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "P84 predecessor of P184",
    overlapNotes: "Ready-for-MEL overlaps P107",
    retirementRecommendation: "retire_later",
  },
  {
    writerId: "candidate-onboarding-engine",
    module: "candidate-onboarding-engine",
    filePaths: [
      "src/lib/candidate-onboarding-engine/run-candidate-onboarding.ts",
      "src/lib/candidate-onboarding-engine/process-signature-status.ts",
      "src/app/api/candidates/onboarding/run/route.ts",
    ],
    statesWritable: ["Ready for MEL", "Signed", "Paperwork Needed"],
    ownedTransitions: ["Signed→Ready for MEL"],
    allowedSourceStates: ["Signed", "Awaiting DD Verification"],
    allowedDestinationStates: ["Ready for MEL"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/candidates/onboarding/run",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: null,
    conflictGroup: "signature_to_mel",
    priority: 66,
    deprecationStatus: "active",
    productionUsage: "onboarding / Ready for MEL",
    overlapNotes: "Overlaps P107 and hiring automation",
    retirementRecommendation: "keep",
  },
  {
    writerId: "workflow-onboarding-reconciliation",
    module: "workflow-onboarding-reconciliation",
    filePaths: [
      "src/lib/workflow-onboarding-reconciliation/reconcile-workflow-from-onboarding.ts",
    ],
    statesWritable: ["Paperwork Sent", "Signed", "Ready for MEL"],
    ownedTransitions: ["onboarding→workflow_reconcile"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["Paperwork Sent", "Signed", "Ready for MEL"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "reconcile",
    entryPoint: "reconcileWorkflowFromOnboarding",
    idempotency: "yes",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "signature_to_mel",
    priority: 62,
    deprecationStatus: "active",
    productionUsage: "durability repair path",
    overlapNotes: "Overlaps webhook/monitor",
    retirementRecommendation: "keep",
  },
  {
    writerId: "candidate-ingestion-backfill",
    module: "candidate-ingestion",
    filePaths: [
      "src/lib/candidate-ingestion/backfill-workflow-records.ts",
    ],
    statesWritable: ["Applied", "Needs Review", "Qualified", "Paperwork Needed"],
    ownedTransitions: ["Breezy→workflow_seed"],
    allowedSourceStates: ["*"],
    allowedDestinationStates: ["Applied", "Needs Review", "Qualified"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "ingestion",
    entryPoint: "backfillWorkflowRecordsForCandidates",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: null,
    conflictGroup: "breezy_ingestion",
    priority: 58,
    deprecationStatus: "active",
    productionUsage: "Breezy→workflow seed",
    overlapNotes: "Overlaps P175",
    retirementRecommendation: "keep",
  },
  {
    writerId: "hiring-automation-engine",
    module: "hiring-automation-engine",
    filePaths: [
      "src/lib/hiring-automation-engine/execute-automation-run.ts",
      "src/app/api/hiring-automation/runs/route.ts",
    ],
    statesWritable: ["Paperwork Sent", "Ready for MEL"],
    ownedTransitions: ["Signed→Ready for MEL", "Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed", "Signed"],
    allowedDestinationStates: ["Paperwork Sent", "Ready for MEL"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "API",
    entryPoint: "/api/hiring-automation/runs",
    idempotency: "partial",
    auditSupport: "yes",
    featureFlag: null,
    conflictGroup: "signature_to_mel",
    priority: 64,
    deprecationStatus: "active",
    productionUsage: "hiring automation MEL/send",
    overlapNotes: "Overlaps onboarding/P107",
    retirementRecommendation: "keep",
  },
  {
    writerId: "direct-deposit-workflow",
    module: "direct-deposit-workflow",
    filePaths: [
      "src/lib/direct-deposit-workflow.ts",
      "src/app/api/onboarding/direct-deposit/route.ts",
    ],
    statesWritable: ["Awaiting DD Verification", "directDepositStatus"],
    ownedTransitions: ["Signed→Awaiting DD Verification"],
    allowedSourceStates: ["Signed"],
    allowedDestinationStates: ["Awaiting DD Verification"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "webhook/API",
    entryPoint: "requestDirectDepositAfterPaperworkSigned",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: "DIRECT_DEPOSIT_EMAIL_MODE",
    conflictGroup: "signature_to_mel",
    priority: 67,
    deprecationStatus: "active",
    productionUsage: "post-sign DD path",
    overlapNotes: "Between Signed and Ready for MEL",
    retirementRecommendation: "keep",
  },
  {
    writerId: "p182-scoped-operator-live-send",
    module: "P182 scoped operator live send",
    filePaths: ["scripts/p182-scoped-operator-live-send.ts"],
    statesWritable: ["Paperwork Sent via P159"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "script",
    entryPoint: "scripts/p182-scoped-operator-live-send.ts",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: "P154_CONTINUOUS_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 35,
    deprecationStatus: "legacy_active",
    productionUsage: "one-shot operator send",
    overlapNotes: "Overlaps P183/P185",
    retirementRecommendation: "freeze_later",
  },
  {
    writerId: "p183-final-scoped-operator-send",
    module: "P183 final scoped operator send",
    filePaths: ["scripts/p183-final-scoped-operator-send.ts"],
    statesWritable: ["Paperwork Sent"],
    ownedTransitions: ["Paperwork Needed→Paperwork Sent"],
    allowedSourceStates: ["Paperwork Needed"],
    allowedDestinationStates: ["Paperwork Sent"],
    sourceOfAuthority: "production",
    productionAuthoritative: true,
    shadowOnly: false,
    trigger: "script",
    entryPoint: "scripts/p183-final-scoped-operator-send.ts",
    idempotency: "partial",
    auditSupport: "partial",
    featureFlag: "P154_CONTINUOUS_ENABLED",
    conflictGroup: "paperwork_send",
    priority: 10,
    deprecationStatus: "deprecated_still_referenced",
    productionUsage: "hard-coded one-shot send",
    overlapNotes: "One-shot; retire after P185",
    retirementRecommendation: "retire_later",
  },
] as const;

export const P1864_SCHEDULER_REGISTRY: readonly P1864SchedulerRecord[] = [
  {
    schedulerId: "p185-cron-api",
    type: "cron-route",
    cadence: "*/10 * * * *",
    trigger: "external cron → API",
    entryPoint: "src/app/api/cron/p185-paperwork-automation/route.ts",
    candidateScope: "P185 rollout cohort / queue",
    lockOrLease: "partial",
    storageBackend: "P185 durable (Neon/PGlite)",
    timeoutBehavior: "maxDuration 60s",
    overlapRisk: "high",
    duplicateProcessingRisk: "medium",
    featureFlag: "P185_PRODUCTION_AUTOMATION_ENABLED",
    relatedWriterIds: ["p185-production-paperwork-runner", "p184-autonomous-paperwork-send-engine"],
  },
  {
    schedulerId: "p125-production-runner-interval",
    type: "in-process-interval",
    cadence: "5m",
    trigger: "setInterval in-process",
    entryPoint: "src/lib/p125-autonomous-paperwork-production-runner/run-production-runner.ts",
    candidateScope: "paperwork-needed candidates",
    lockOrLease: "none",
    storageBackend: "local runner state",
    timeoutBehavior: "cycle timeout varies",
    overlapRisk: "critical",
    duplicateProcessingRisk: "high",
    featureFlag: "P125_RUNNER_CONTINUOUS_ENABLED",
    relatedWriterIds: ["p125-production-runner"],
  },
  {
    schedulerId: "p136-paperwork-scheduler-interval",
    type: "in-process-interval",
    cadence: "5m",
    trigger: "setInterval via API start",
    entryPoint: "src/app/api/autonomous-paperwork-scheduler/start/route.ts",
    candidateScope: "paperwork-needed candidates",
    lockOrLease: "none",
    storageBackend: "scheduler state file",
    timeoutBehavior: "cycle timeout varies",
    overlapRisk: "critical",
    duplicateProcessingRisk: "high",
    featureFlag: null,
    relatedWriterIds: ["p136-paperwork-scheduler"],
  },
  {
    schedulerId: "p1061-runner-interval",
    type: "in-process-interval",
    cadence: "5m",
    trigger: "setInterval via API start",
    entryPoint: "src/app/api/autonomous-paperwork-runner/start/route.ts",
    candidateScope: "autonomous paperwork queue",
    lockOrLease: "none",
    storageBackend: "runner state",
    timeoutBehavior: "full reconcile 24h",
    overlapRisk: "critical",
    duplicateProcessingRisk: "high",
    featureFlag: "AUTONOMOUS_PAPERWORK_RUNNER_SCHEDULE_ENABLED",
    relatedWriterIds: ["p1061-autonomous-paperwork-runner", "p106-autonomous-paperwork-engine"],
  },
  {
    schedulerId: "p107-paperwork-monitor-interval",
    type: "in-process-interval",
    cadence: "5m",
    trigger: "setInterval",
    entryPoint: "src/lib/paperwork-monitor/run-paperwork-monitor-cycle.ts",
    candidateScope: "sent/unsigned paperwork",
    lockOrLease: "none",
    storageBackend: "workflow store",
    timeoutBehavior: "cycle timeout varies",
    overlapRisk: "medium",
    duplicateProcessingRisk: "medium",
    featureFlag: null,
    relatedWriterIds: ["p107-paperwork-monitor", "dropbox-sign-webhook"],
  },
  {
    schedulerId: "p148-orchestrator-interval",
    type: "host-interval",
    cadence: "5m",
    trigger: "host script interval",
    entryPoint: "scripts/p148-autonomous-recruiting-orchestrator.ts",
    candidateScope: "recruiting automation cohort",
    lockOrLease: "none",
    storageBackend: "orchestrator store",
    timeoutBehavior: "unknown",
    overlapRisk: "high",
    duplicateProcessingRisk: "high",
    featureFlag: "AUTONOMOUS_RECRUITING_ENABLED",
    relatedWriterIds: ["p148-autonomous-recruiting-orchestrator"],
  },
  {
    schedulerId: "p1547-continuous-daemon",
    type: "host-daemon",
    cadence: "10m",
    trigger: "daemon script",
    entryPoint: "scripts/p154.7-continuous-runner.ts",
    candidateScope: "full recruiting pipeline",
    lockOrLease: "partial",
    storageBackend: "runner + workflow store",
    timeoutBehavior: "P154_STOP_ON_ERROR",
    overlapRisk: "critical",
    duplicateProcessingRisk: "high",
    featureFlag: "P154_CONTINUOUS_ENABLED",
    relatedWriterIds: ["p1547-continuous-recruiting-runner", "p154-controlled-autopilot"],
  },
  {
    schedulerId: "p169-orchestrator-host",
    type: "host-interval",
    cadence: "7m",
    trigger: "host script interval",
    entryPoint: "scripts/p169-orchestrator-host.ts",
    candidateScope: "orchestrator evaluation set",
    lockOrLease: "partial",
    storageBackend: "P169 evaluation store",
    timeoutBehavior: "cycle timeout varies",
    overlapRisk: "critical",
    duplicateProcessingRisk: "high",
    featureFlag: "P169_ORCHESTRATOR_ENABLED",
    relatedWriterIds: ["p169-recruiting-orchestrator", "p159-operations-control-center"],
  },
  {
    schedulerId: "p171-lifecycle-host",
    type: "host-interval",
    cadence: "15m",
    trigger: "host/API control",
    entryPoint: "src/app/api/recruiting/lifecycle-manager/control/route.ts",
    candidateScope: "P171 lifecycle cohort",
    lockOrLease: "partial",
    storageBackend: "P171 lifecycle store",
    timeoutBehavior: "cycle timeout varies",
    overlapRisk: "high",
    duplicateProcessingRisk: "medium",
    featureFlag: "P171_LIFECYCLE_ENABLED",
    relatedWriterIds: ["p171-lifecycle-manager"],
  },
  {
    schedulerId: "dropbox-webhook-retries",
    type: "webhook-retry",
    cadence: "provider retry policy",
    trigger: "Dropbox Sign webhook",
    entryPoint: "src/app/api/dropbox-sign/webhook/route.ts",
    candidateScope: "envelope events",
    lockOrLease: "partial",
    storageBackend: "workflow store",
    timeoutBehavior: "HTTP retry",
    overlapRisk: "medium",
    duplicateProcessingRisk: "medium",
    featureFlag: null,
    relatedWriterIds: ["dropbox-sign-webhook"],
  },
];

export const REQUIRED_INVENTORY_WRITER_IDS = [
  "p83-candidate-advancement",
  "p106-autonomous-paperwork-engine",
  "p125-production-runner",
  "p148-autonomous-recruiting-orchestrator",
  "p1547-continuous-recruiting-runner",
  "p159-operations-control-center",
  "p169-recruiting-orchestrator",
  "p171-lifecycle-manager",
  "p184-autonomous-paperwork-send-engine",
  "p185-production-paperwork-runner",
  "candidate-workflow-store-core",
  "dropbox-sign-webhook",
  "p186-1-lifecycle-state-machine",
  "p186-3-operator-approval-actions",
] as const;

export function getWriterById(id: string): P1864WriterRecord | undefined {
  return P1864_WRITER_REGISTRY.find((w) => w.writerId === id);
}

export function listWritersByConflictGroup(group: string): P1864WriterRecord[] {
  return P1864_WRITER_REGISTRY.filter((w) => w.conflictGroup === group);
}
