import type { TestCohortApplicant } from "@/lib/test-cohort-validation/types";

export const P103_TEST_APPLICANTS: TestCohortApplicant[] = [
  {
    key: "malcolm-cooper",
    name: "Malcolm Cooper",
    phone: "724-557-8197",
    city: "Washington",
    state: "PA",
    email: "malcolmjcoope0809@gmail.com",
    positionTitle: "Retail Merchandiser - Western PA & WV Area",
    cluster: "washington_pa_retail_merchandiser",
  },
  {
    key: "terrel-andrews",
    name: "Terrel Andrews",
    phone: "724-580-7004",
    city: "Washington",
    state: "PA",
    email: "t3drewz@gmail.com",
    positionTitle: "Retail Merchandiser - Western PA & WV Area",
    cluster: "washington_pa_retail_merchandiser",
  },
  {
    key: "ryley-umbel",
    name: "Ryley Umbel",
    phone: "724-570-1081",
    city: "Washington",
    state: "PA",
    email: "ryleyumbel5@yahoo.com",
    positionTitle: "Retail Merchandiser - Western PA & WV Area",
    cluster: "washington_pa_retail_merchandiser",
  },
  {
    key: "tyesha-evans",
    name: "Tyesha Evans",
    phone: "724-498-7963",
    city: "Washington",
    state: "PA",
    email: "kayvon05@gmial.com",
    positionTitle: "Retail Merchandiser - Western PA & WV Area",
    cluster: "washington_pa_retail_merchandiser",
  },
  {
    key: "lara-gh",
    name: "Lara Gh",
    phone: "646-684-5888",
    city: "Cleveland",
    state: "OH",
    email: "lara.gh88@hotmail.com",
    positionTitle: "Retail Merchandiser - Cleveland Southwest Area",
  },
  {
    key: "alexandra-ridel",
    name: "Alexandra Ridel",
    phone: "440-865-6518",
    city: "Sheffield Village",
    state: "OH",
    email: "alexridel1995@gmail.com",
    positionTitle: "Retail Merchandiser - Lorain County Area",
  },
  {
    key: "darian-taylor-jr",
    name: "Darian Taylor Jr.",
    phone: "740-346-8015",
    city: "Hermitage",
    state: "PA",
    email: "flaminghotcheetos6599@gmail.com",
    positionTitle: "Continuity Merchandiser SF - Hermitage, PA",
  },
  {
    key: "airica-skinner",
    name: "Airica Skinner",
    phone: "330-780-6471",
    city: "West Richfield",
    state: "OH",
    email: "airica1260@yahoo.com",
    positionTitle: "Retail Merchandiser - West Richfield, OH",
    cluster: "west_richfield_oh",
  },
  {
    key: "john-sykes",
    name: "John Sykes",
    phone: "412-608-9745",
    city: "South Side Flats",
    state: "PA",
    email: "johnsykes1225@gmail.com",
    positionTitle: "Retail Merchandiser (Flexible, Project-Based Work)",
  },
  {
    key: "izabella-bilderback",
    name: "Izabella Bilderback",
    phone: "330-410-8848",
    city: "West Richfield",
    state: "OH",
    email: "izbilderback@gmail.com",
    positionTitle: "Retail Merchandiser - West Richfield, OH",
    cluster: "west_richfield_oh",
  },
  {
    key: "chasity-wiggins",
    name: "Chasity Wiggins",
    phone: "234-384-1711",
    city: "West Richfield",
    state: "OH",
    email: "chasitymay1234@gmail.com",
    positionTitle: "Retail Merchandiser - West Richfield, OH",
    cluster: "west_richfield_oh",
  },
];
