import type { ControlledProductionAutopilotCycleReport } from "@/lib/p154-controlled-production-autopilot-activation/types";

export function formatP154ProductionAutopilotMarkdown(
  report: ControlledProductionAutopilotCycleReport,
): string {
  const lines = [
    "# P154 — Controlled Production Autopilot Activation",
    "",
    `Generated: ${report.generatedAt}`,
    `Mode: ${report.dryRun ? "dry run" : "live"}`,
    `Autopilot enabled: **${report.autopilotEnabled}**`,
    `Paused: **${report.paused}**${report.pausedReason ? ` — ${report.pausedReason}` : ""}`,
    "",
    "## System health",
    "",
    `Overall: **${report.health.overallStatus}** (${report.health.healthy ? "PASS" : "FAIL"})`,
    "",
    "| Dependency | Status | Detail |",
    "|------------|--------|--------|",
  ];

  for (const check of report.health.checks) {
    lines.push(`| ${check.label} | ${check.status} | ${check.detail} |`);
  }

  lines.push(
    "",
    "## Enabled features",
    "",
    `- P151 recruiter assignment: ${report.enabledFeatures.p151RecruiterAssignment}`,
    `- P152 immediate paperwork: ${report.enabledFeatures.p152ImmediatePaperwork}`,
    `- Fresh ingestion rescue: ${report.enabledFeatures.freshIngestionRescue}`,
    `- Automatic workflow advancement: ${report.enabledFeatures.automaticWorkflowAdvancement}`,
    `- Webhook completion processing: ${report.enabledFeatures.webhookCompletionProcessing}`,
    `- Duplicate prevention: ${report.enabledFeatures.duplicatePrevention}`,
    `- Continuous ingestion: ${report.enabledFeatures.continuousIngestion}`,
    "",
    "## Production limits",
    "",
    `- Max recruiter assignments per cycle: **${report.limits.maxRecruiterAssignmentsPerCycle}**`,
    `- Max paperwork sends per cycle: **${report.limits.maxPaperworkSendsPerCycle}**`,
    `- Stop on first error: **${report.limits.stopOnFirstError}**`,
    "",
    "## Cycle results",
    "",
    `- Candidates evaluated: **${report.cycle.candidatesEvaluated}**`,
    `- Recruiters assigned: **${report.cycle.recruitersAssigned}**`,
    `- Paperwork sent: **${report.cycle.paperworkSent}**`,
    `- Paperwork skipped: **${report.cycle.paperworkSkipped}**`,
    `- Duplicates prevented: **${report.cycle.duplicatesPrevented}**`,
    `- Failures: **${report.cycle.failures}**`,
    `- Execution time: **${report.cycle.executionTimeMs}ms**`,
    `- Webhook status: ${report.cycle.webhookStatus}`,
    `- Queue remaining: **${report.cycle.queueRemaining}**`,
    "",
    "## Live dashboard metrics",
    "",
    "| Metric | Value |",
    "|--------|-------|",
    `| Candidates evaluated | ${report.dashboard.candidatesEvaluated} |`,
    `| Recruiters assigned | ${report.dashboard.recruitersAssigned} |`,
    `| Paperwork sent | ${report.dashboard.paperworkSent} |`,
    `| Paperwork completed | ${report.dashboard.paperworkCompleted} |`,
    `| Duplicates prevented | ${report.dashboard.duplicatesPrevented} |`,
    `| Failures | ${report.dashboard.failures} |`,
    `| Webhook completions | ${report.dashboard.webhookCompletions} |`,
    `| Average processing time | ${report.dashboard.averageProcessingTimeMs}ms |`,
    `| Queue depth | ${report.dashboard.queueDepth} |`,
    `| Last successful cycle | ${report.dashboard.lastSuccessfulCycleAt ?? "—"} |`,
    "",
    "## Safety",
    "",
    `- Breezy writes: **no**`,
    `- Breezy stage movement: **no**`,
    `- executeBatch called: **no**`,
    `- Duplicate prevention: **active**`,
    `- Audit logging: **enabled**`,
    "",
    "## Rollback recommendation",
    "",
    report.rollbackRecommendation,
    "",
  );
  return `${lines.join("\n")}\n`;
}
