import type { P1544CycleReport } from "@/lib/p154-full-candidate-backfill-continuous-processing/types";

export function formatP1544BackfillContinuousMarkdown(report: P1544CycleReport): string {
  const b = report.backfill;
  const c = report.classification;
  const cycle = report.controlledCycle;
  const d = report.dashboard;
  const lines = [
    "# P154.4 — Full Candidate Backfill & Continuous Processing",
    "",
    `Generated: ${report.generatedAt}`,
    `Mode: **${report.dryRun ? "dry run" : "live"}**`,
    report.skippedOverlap ? "Skipped: overlapping run lock." : "",
    "",
    "## Phase 1 — Full Breezy backfill",
    "",
    `- Total positions scanned: **${b.totalPositionsScanned}**`,
    `- Active positions scanned: **${b.activePositionsScanned}**`,
    `- Closed positions scanned: **${b.closedPositionsScanned}**`,
    `- Archived positions scanned: **${b.archivedPositionsScanned}**`,
    `- Total candidates found: **${b.totalCandidatesFound}**`,
    `- Candidates since ${b.backfillSince}: **${b.candidatesSinceJune}**`,
    `- Already in ingestion store: **${b.candidatesAlreadyInStore}**`,
    `- Newly discovered: **${b.newlyDiscoveredCandidates}**`,
    `- Missing before backfill: **${b.candidatesMissingBeforeBackfill}**`,
    `- Merged into store: **${b.mergedIntoStore}**`,
    `- Workflows created: **${b.workflowsCreated}**`,
    `- Backfill time: **${b.executionTimeMs}ms**`,
    "",
    "## Phase 2 — Eligibility classification",
    "",
    `- Total classified: **${c.totalClassified}**`,
    `- Eligible for paperwork: **${c.buckets.eligible_for_paperwork}**`,
    `- Already sent: **${c.buckets.already_sent}**`,
    `- Active signature request: **${c.buckets.active_signature_request}**`,
    `- Already signed: **${c.buckets.already_signed}**`,
    `- Duplicate: **${c.buckets.duplicate}**`,
    `- Invalid email: **${c.buckets.invalid_email}**`,
    `- Disqualified / archived: **${c.buckets.disqualified_archived}**`,
    `- Needs recruiter assignment: **${c.buckets.needs_recruiter_assignment}**`,
    `- Manual review: **${c.buckets.manual_review}**`,
    `- Do not send: **${c.buckets.do_not_send}**`,
    "",
    "## Phase 3 — Controlled send loop",
    "",
    cycle
      ? [
          `- Candidates evaluated: **${cycle.cycle.candidatesEvaluated}**`,
          `- Recruiters assigned: **${cycle.cycle.recruitersAssigned}**`,
          `- Paperwork sent: **${cycle.cycle.paperworkSent}**`,
          `- Paperwork skipped: **${cycle.cycle.paperworkSkipped}**`,
          `- Duplicates prevented: **${cycle.cycle.duplicatesPrevented}**`,
          `- Failures: **${cycle.cycle.failures}**`,
          `- Queue remaining: **${cycle.cycle.queueRemaining}**`,
          `- Execution time: **${cycle.cycle.executionTimeMs}ms**`,
        ].join("\n")
      : "—",
    "",
    "## Phase 6 — Dashboard",
    "",
    `- Total candidates scanned: **${d.totalCandidatesScanned}**`,
    `- Total since June: **${d.totalSinceJune}**`,
    `- New candidates discovered: **${d.newCandidatesDiscovered}**`,
    `- Eligible today: **${d.eligibleToday}**`,
    `- Sent today: **${d.sentToday}**`,
    `- Signed today: **${d.signedToday}**`,
    `- Active signature requests: **${d.activeSignatureRequests}**`,
    `- Duplicates prevented: **${d.duplicatesPrevented}**`,
    `- Queue remaining: **${d.queueRemaining}**`,
    `- Next scheduled run: **${d.nextScheduledRunAt ?? "—"}**`,
    `- Last successful run: **${d.lastSuccessfulRunAt ?? "—"}**`,
    "",
    "## Safety",
    "",
    "- Duplicate prevention: active",
    "- Overlap lock: active",
    "- Stop on first error: yes",
    "- Breezy writes: no",
    "- Max assignments per cycle: 25",
    "- Max sends per cycle: 10",
    "",
  ];
  return `${lines.filter((line) => line !== "").join("\n")}\n`;
}
