import type { AutomationRule } from "@/lib/notification-engine/types";

export const COVERAGE_RISK_NOTIFICATION_THRESHOLD = 60;
export const RECRUITER_WORKLOAD_NOTIFICATION_THRESHOLD = 75;
export const PAPERWORK_PENDING_NOTIFICATION_HOURS = 48;
export const CANDIDATE_AGING_NOTIFICATION_DAYS = 3;
export const OPEN_CALL_INACTIVITY_DAYS = 5;

export const AUTOMATION_RULES: AutomationRule[] = [
  {
    id: "recruiter-new-applicant",
    label: "New applicant assigned",
    trigger: "candidate.assigned",
    condition: "Applicant assigned today to recruiter queue",
    action: "Surface in-app notification to assigned recruiter",
    severity: "info",
    recipient: "recruiter",
    channels: ["in-app", "email"],
    enabled: true,
  },
  {
    id: "recruiter-follow-up-due",
    label: "Follow-up due",
    trigger: "candidate.follow_up_due",
    condition: "Follow-up flag overdue or due within 12 hours",
    action: "Prompt recruiter to contact candidate",
    severity: "warning",
    recipient: "recruiter",
    channels: ["in-app", "sms"],
    enabled: true,
  },
  {
    id: "recruiter-candidate-aging",
    label: "Candidate aging",
    trigger: "candidate.applied_aging",
    condition: `Applied stage aging exceeds ${CANDIDATE_AGING_NOTIFICATION_DAYS} days`,
    action: "Escalate aging applicant in recruiter queue",
    severity: "warning",
    recipient: "recruiter",
    channels: ["in-app"],
    enabled: true,
  },
  {
    id: "recruiter-paperwork-not-started",
    label: "Paperwork not started",
    trigger: "candidate.paperwork_needed",
    condition: "Qualified candidate without paperwork sent",
    action: "Prompt recruiter to send onboarding packet",
    severity: "warning",
    recipient: "recruiter",
    channels: ["in-app", "email"],
    enabled: true,
  },
  {
    id: "recruiter-paperwork-pending",
    label: "Paperwork pending",
    trigger: "candidate.paperwork_pending",
    condition: `Paperwork sent but unsigned for ${PAPERWORK_PENDING_NOTIFICATION_HOURS}+ hours`,
    action: "Remind recruiter to chase paperwork completion",
    severity: "critical",
    recipient: "recruiter",
    channels: ["in-app", "email", "sms"],
    enabled: true,
  },
  {
    id: "dm-coverage-risk",
    label: "Coverage risk threshold",
    trigger: "territory.coverage_risk",
    condition: `Coverage risk score exceeds ${COVERAGE_RISK_NOTIFICATION_THRESHOLD}`,
    action: "Alert DM to review staffing coverage",
    severity: "critical",
    recipient: "dm",
    channels: ["in-app", "email", "teams"],
    enabled: true,
  },
  {
    id: "dm-zero-applicant-jobs",
    label: "Zero-applicant jobs",
    trigger: "job.zero_applicants",
    condition: "Published job has zero applicants",
    action: "Recommend additional ads or sourcing",
    severity: "warning",
    recipient: "dm",
    channels: ["in-app", "email"],
    enabled: true,
  },
  {
    id: "dm-low-applicant-flow",
    label: "Low applicant flow",
    trigger: "job.low_applicant_flow",
    condition: "Job has fewer than 2 applicants",
    action: "Flag low-flow posting to DM",
    severity: "info",
    recipient: "dm",
    channels: ["in-app"],
    enabled: true,
  },
  {
    id: "dm-open-calls-inactive",
    label: "Open calls inactive",
    trigger: "mel.open_call_inactive",
    condition: `Open MEL call with no recruiter activity for ${OPEN_CALL_INACTIVITY_DAYS}+ days`,
    action: "Request recruiter engagement on open call",
    severity: "warning",
    recipient: "dm",
    channels: ["in-app", "teams"],
    enabled: true,
  },
  {
    id: "dm-territory-health-declining",
    label: "Territory health declining",
    trigger: "territory.health_declining",
    condition: "Applicant velocity declining week over week",
    action: "Surface territory health warning to DM",
    severity: "warning",
    recipient: "dm",
    channels: ["in-app"],
    enabled: true,
  },
  {
    id: "executive-critical-territory",
    label: "Critical territory",
    trigger: "executive.territory_risk",
    condition: "Territory in top risk rollup with critical coverage",
    action: "Executive review of territory staffing plan",
    severity: "critical",
    recipient: "executive",
    channels: ["in-app", "email", "teams"],
    enabled: true,
  },
  {
    id: "executive-recruiter-workload",
    label: "High recruiter workload",
    trigger: "executive.recruiter_workload",
    condition: `Recruiter workload score exceeds ${RECRUITER_WORKLOAD_NOTIFICATION_THRESHOLD}`,
    action: "Rebalance recruiter assignments",
    severity: "warning",
    recipient: "executive",
    channels: ["in-app", "email"],
    enabled: true,
  },
  {
    id: "executive-hiring-velocity-decline",
    label: "Hiring velocity decline",
    trigger: "executive.hiring_velocity",
    condition: "Organization applicant velocity declining",
    action: "Executive pipeline review",
    severity: "warning",
    recipient: "executive",
    channels: ["in-app"],
    enabled: true,
  },
  {
    id: "executive-open-calls-at-risk",
    label: "Open calls at risk",
    trigger: "executive.open_calls_risk",
    condition: "High count of unstaffed high-priority MEL opportunities",
    action: "Prioritize open call staffing",
    severity: "critical",
    recipient: "executive",
    channels: ["in-app", "teams"],
    enabled: true,
  },
];

export function getAutomationRule(ruleId: string): AutomationRule | undefined {
  return AUTOMATION_RULES.find((rule) => rule.id === ruleId);
}
